# Generated by Django 5.2.1 on 2025-07-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_horariosasignados_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupos',
            options={'ordering': ['-grupo_id'], 'verbose_name': 'Grupo/Sección', 'verbose_name_plural': 'Grupos/Secciones'},
        ),
    ]
